baseURL = 'https://luiseduardovalverderamos.github.io/mypage/'
languageCode = 'en-us'
title = 'Luis Valverde Ramos'
theme = "hugo-noir"

# Taxonomy configuration
[taxonomies]
  category = "categories"
  tag = "tags"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]

  [languages.en]
    languageName = "English"
    title = "Luis Valverde Ramos"
    weight = 1
    contentDir = "content/en"
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "About"
        pageRef = "/about"
        weight = 1
      [[languages.en.menu.main]]
        name = "Education"
        pageRef = "/education"
        weight = 2
      [[languages.en.menu.main]]
        name = "Experience"
        pageRef = "/experience"
        weight = 3
      [[languages.en.menu.main]]
        name = "Projects"
        pageRef = "/projects"
        weight = 5
      [[languages.en.menu.main]]
        name = "Publications"
        pageRef = "/publications"
        weight = 6
      [[languages.en.menu.main]]
        name = "Media"
        pageRef = "/media"
        weight = 7
      [[languages.en.menu.main]]
        name = "Contact"
        pageRef = "/contact"
        weight = 8

  [languages.es]
    languageName = "Español"
    title = "Luis Valverde Ramos"
    weight = 2
    contentDir = "content/es"
    [languages.es.menu]
      [[languages.es.menu.main]]
        name = "Sobre Mí"
        pageRef = "/about"
        weight = 1
      [[languages.es.menu.main]]
        name = "Educación"
        pageRef = "/education"
        weight = 2
      [[languages.es.menu.main]]
        name = "Experiencia"
        pageRef = "/experience"
        weight = 3
      [[languages.es.menu.main]]
        name = "Proyectos"
        pageRef = "/projects"
        weight = 5
      [[languages.es.menu.main]]
        name = "Publicaciones"
        pageRef = "/publications"
        weight = 6
      [[languages.es.menu.main]]
        name = "Media"
        pageRef = "/media"
        weight = 7
      [[languages.es.menu.main]]
        name = "Contacto"
        pageRef = "/contact"
        weight = 8

[params]
  name = "Luis Valverde Ramos"
  location = "Lima, Perú"
  description = "Political Scientist | Mixed Methods & ML | Public Policy | Regulatory Analysis | Debate"
  profile_image = "/images/profile.jpeg"
  # Social links
  github = "https://github.com/LuisEduardoValverdeRamos"
  linkedin = "https://www.linkedin.com/in/luisvalverderamos/"
  twitter = "https://x.com/LuisValverde06"
  email = "luis.valverde@pucp.edu.pe"
