baseURL = 'https://luiseduardovalverderamos.github.io/'
languageCode = 'en-us'
title = 'Luis Valverde Ramos'
theme = "hugo-noir"

defaultContentLanguage = "en"

# Taxonomy configuration
[taxonomies]
  category = "categories"
  tag = "tags"

[languages]

  [languages.en]
    languageName = "English"
    title = "Luis Valverde Ramos"
    weight = 1
    contentDir = "content/en"
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "About"
        pageRef = "/about"
        weight = 1
      [[languages.en.menu.main]]
        name = "Experience"
        pageRef = "/experience"
        weight = 2
      [[languages.en.menu.main]]
        name = "Research"
        pageRef = "/projects"
        weight = 3
      [[languages.en.menu.main]]
        name = "Writing & Media"
        pageRef = "/publications"
        weight = 4
      [[languages.en.menu.main]]
        name = "Contact"
        pageRef = "/contact"
        weight = 5

  [languages.es]
    languageName = "Español"
    title = "Luis Valverde Ramos"
    weight = 2
    contentDir = "content/es"
    [languages.es.menu]
      [[languages.es.menu.main]]
        name = "Sobre Mí"
        pageRef = "/about"
        weight = 1
      [[languages.es.menu.main]]
        name = "Experiencia"
        pageRef = "/experience"
        weight = 2
      [[languages.es.menu.main]]
        name = "Investigación"
        pageRef = "/projects"
        weight = 3
      [[languages.es.menu.main]]
        name = "Escritos y Medios"
        pageRef = "/publications"
        weight = 4
      [[languages.es.menu.main]]
        name = "Contacto"
        pageRef = "/contact"
        weight = 5

[params]
  name = "Luis Valverde Ramos"
  location = "Piura, Perú"
  description = "Political Scientist (PUCP) | Mixed Methods | Electoral Politics · Public Policy"
  profile_image = "/images/profile.jpeg"
  # Social links
  github = "https://github.com/LuisEduardoValverdeRamos"
  linkedin = "https://www.linkedin.com/in/luisvalverderamos/"
  twitter = "https://x.com/LuisValverde06"
  email = "luis.valverde@pucp.edu.pe"
